terminal_title_flag = ""
locale = ""
close_when_open = true
theme = "default"
monitor = ""
hotreload_theme = true
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = true
theme_location = []
plugin_location = []

[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
dynamic_sub = true
keyboard_scroll_style = "vim"
max_entries = 200
show_initial_entries = true
single_click = true
visibility_threshold = 20
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = "Search..."
delay = 0
resume_last_query = false

[builtins.applications]
weight = 5
name = "applications"
placeholder = "Applications"
prioritize_new = true
hide_actions_with_empty_query = true
context_aware = true
refresh = true
show_sub_when_single = true
show_icon_when_single = true
show_generic = true
history = true
icon = "applications-other"

[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.calc]
require_number = true
weight = 5
name = "Calculator"
icon = "accessories-calculator"
placeholder = "Calculator"
min_chars = 3

[builtins.websearch]
keep_selection = true
weight = 5
icon = "applications-internet"
name = "Websearch"
placeholder = "Websearch..."

[builtins.websearch.entries]
name = "Kagi"
url = "https://kagi.com/search?q=%TERM%"

[builtins.dmenu]
hidden = true
weight = 5
name = "dmenu"
placeholder = "Dmenu"
switcher_only = true
show_icon_when_single = true

[builtins.switcher]
weight = 5
name = "switcher"
placeholder = "Switcher"
prefix = "/"
